In [1]:
# !python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

!python -m pip install -U pandas matplotlib "cython<3.1" poetry-core
!python -m pip install --no-build-isolation python-woc

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (3.0.6)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (3.11.2)
Requirement already satisfied: cython<3.1 in /opt/anaconda3/lib/python3.13/site-packages (3.0.12)
Requirement already satisfied: poetry-core in /opt/anaconda3/lib/python3.13/site-packages (2.5.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: python-woc in /opt/anaconda3/lib/python3.13/site-packages (0.4.1)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /opt/anaconda3/lib/python3.13/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /opt/anaconda3/lib/python3.13/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /opt/anaconda3/lib/python3.13/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /opt/anaconda3/lib/python3.13/site-packages (from python-woc) (4.67.1)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.13.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)

In [2]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = ['delftdata/valentine', 'darioizzo/geodesyNets', 'Antonio-JP/dd_functions',
            'ANYbotics/elevation_mapping', 'singmann/afex', 'opensafely/antibody-and-antiviral-deployment',
            'sebmart/TaxiSimulation', 'brainstorm-tools/brainstorm3', 'langurmonkey/gaiasky',
            'jump-dev/SumOfSquares.jl']
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1              project
0  00c5bbd0d4fdddc2a6f2ffec96b4a6472b4c7bef  delftdata_valentine

In [3]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  6%|▌         | 137/2243 [02:26<38:15,  1.09s/it]

Got Errors {'088c72792e59048c961e350becd1d9abffa65fad': 'Key 088c72792e59048c961e350becd1d9abffa65fad not found in /da5_fast/All.sha1c/commit_8.tch'}

  6%|▋         | 144/2243 [02:33<37:39,  1.08s/it]

Got Errors {'1fb51ebb1f409dcb73a0b76ce609d058fc65e74c': 'Key 1fb51ebb1f409dcb73a0b76ce609d058fc65e74c not found in /da5_fast/All.sha1c/commit_31.tch'}

  7%|▋         | 147/2243 [02:37<37:34,  1.08s/it]

Got Errors {'2a913f940fe160b89b0800f6bc8752921a4f95b8': 'Key 2a913f940fe160b89b0800f6bc8752921a4f95b8 not found in /da5_fast/All.sha1c/commit_42.tch'}

  7%|▋         | 157/2243 [02:47<37:24,  1.08s/it]

Got Errors {'4aa8b133c5045d07aaf151cc9a375edbb603d492': 'Key 4aa8b133c5045d07aaf151cc9a375edbb603d492 not found in /da5_fast/All.sha1c/commit_74.tch'}

  7%|▋         | 165/2243 [02:56<37:17,  1.08s/it]

Got Errors {'66f6a3dcc11e680c86bde15d895cd03aa6f3c343': 'Key 66f6a3dcc11e680c86bde15d895cd03aa6f3c343 not found in /da5_fast/All.sha1c/commit_102.tch'}

  7%|▋         | 167/2243 [02:58<37:18,  1.08s/it]

Got Errors {'6e9755a806de3bc6e17394ebf4a15017aeec1648': 'Key 6e9755a806de3bc6e17394ebf4a15017aeec1648 not found in /da5_fast/All.sha1c/commit_110.tch'}

  7%|▋         | 168/2243 [02:59<37:11,  1.08s/it]

Got Errors {'7056f0e220a03fa59a8eed2110926aefa90d1085': 'Key 7056f0e220a03fa59a8eed2110926aefa90d1085 not found in /da5_fast/All.sha1c/commit_112.tch'}

  8%|▊         | 171/2243 [03:02<37:06,  1.07s/it]

Got Errors {'7cd078669435a7a6683b6b4afddddcbeb02683a3': 'Key 7cd078669435a7a6683b6b4afddddcbeb02683a3 not found in /da5_fast/All.sha1c/commit_124.tch'}

  8%|▊         | 182/2243 [03:14<36:44,  1.07s/it]

Got Errors {'9fd5b16556f665c49f51ab8e9369a9bb8cd80715': 'Key 9fd5b16556f665c49f51ab8e9369a9bb8cd80715 not found in /da5_fast/All.sha1c/commit_31.tch'}

  8%|▊         | 183/2243 [03:15<36:40,  1.07s/it]

Got Errors {'a42878f7aade46439fc3f4de2870d3f0f4fa0b03': 'Key a42878f7aade46439fc3f4de2870d3f0f4fa0b03 not found in /da5_fast/All.sha1c/commit_36.tch'}

  8%|▊         | 188/2243 [03:21<36:36,  1.07s/it]

Got Errors {'b1f26a0e0aae4d103ab7b4ae332670db0f295b46': 'Key b1f26a0e0aae4d103ab7b4ae332670db0f295b46 not found in /da5_fast/All.sha1c/commit_49.tch'}

  8%|▊         | 189/2243 [03:22<36:35,  1.07s/it]

Got Errors {'b4a2640db1cfb6464b0cad0619f552aa23afcc2c': 'Key b4a2640db1cfb6464b0cad0619f552aa23afcc2c not found in /da5_fast/All.sha1c/commit_52.tch'}

  9%|▊         | 193/2243 [03:26<36:31,  1.07s/it]

Got Errors {'c30097d2b1346ec82b024ccaac0e1818bf54ddb3': 'Key c30097d2b1346ec82b024ccaac0e1818bf54ddb3 not found in /da5_fast/All.sha1c/commit_67.tch'}

  9%|▊         | 195/2243 [03:28<36:28,  1.07s/it]

Got Errors {'ccc1927d956f4337aeae939162da65e2a3685db0': 'Key ccc1927d956f4337aeae939162da65e2a3685db0 not found in /da5_fast/All.sha1c/commit_76.tch'}

  9%|▉         | 201/2243 [03:34<36:23,  1.07s/it]

Got Errors {'e363eaa2bf8df7bacc50163fbc60ab5ab40f9678': 'Key e363eaa2bf8df7bacc50163fbc60ab5ab40f9678 not found in /da5_fast/All.sha1c/commit_99.tch'}

  9%|▉         | 204/2243 [03:38<36:28,  1.07s/it]

Got Errors {'edbc5517d308f9a84f6931b2924171cec21782f9': 'Key edbc5517d308f9a84f6931b2924171cec21782f9 not found in /da5_fast/All.sha1c/commit_109.tch'}

 11%|█         | 251/2243 [04:28<35:37,  1.07s/it]

Got Errors {'8abd17d2ca1222ccbb0bc69fcf4c2e2a78b2a6c2': 'Key 8abd17d2ca1222ccbb0bc69fcf4c2e2a78b2a6c2 not found in /da5_fast/All.sha1c/commit_10.tch'}

 18%|█▊        | 393/2243 [07:01<33:11,  1.08s/it]

Got Errors {'00137fa7c3186fb1285a017d2793c142eebb353b': 'Key 00137fa7c3186fb1285a017d2793c142eebb353b not found in /da5_fast/All.sha1c/commit_0.tch'}

 19%|█▉        | 429/2243 [07:40<32:35,  1.08s/it]

Got Errors {'0cff98fde1295d4e9cf6ca250c3b5089475116ce': 'Key 0cff98fde1295d4e9cf6ca250c3b5089475116ce not found in /da5_fast/All.sha1c/commit_12.tch'}

 20%|█▉        | 442/2243 [07:54<32:16,  1.08s/it]

Got Errors {'114c2c2ad19c1f45102fb61afca2216b620668b7': 'Key 114c2c2ad19c1f45102fb61afca2216b620668b7 not found in /da5_fast/All.sha1c/commit_17.tch'}

 24%|██▍       | 549/2243 [09:49<30:25,  1.08s/it]

Got Errors {'33291f25ce83109afe8d26931136b8b6f6778071': 'Key 33291f25ce83109afe8d26931136b8b6f6778071 not found in /da5_fast/All.sha1c/commit_51.tch'}

 25%|██▍       | 555/2243 [09:56<30:18,  1.08s/it]

Got Errors {'351e8eba15a6ce3136e7e87449e06e2f551daa53': 'Key 351e8eba15a6ce3136e7e87449e06e2f551daa53 not found in /da5_fast/All.sha1c/commit_53.tch'}

 29%|██▉       | 653/2243 [11:42<28:27,  1.07s/it]

Got Errors {'545589f13089b69e4c3e686575ca0a7acc3b684a': 'Key 545589f13089b69e4c3e686575ca0a7acc3b684a not found in /da5_fast/All.sha1c/commit_84.tch'}

 35%|███▍      | 774/2243 [13:52<26:32,  1.08s/it]

Got Errors {'7c3b057c28145a49de6ae9f9d7de919c59537e82': 'Key 7c3b057c28145a49de6ae9f9d7de919c59537e82 not found in /da5_fast/All.sha1c/commit_124.tch'}

 48%|████▊     | 1071/2243 [19:13<21:03,  1.08s/it]

Got Errors {'de5aa1ad8b41d89850348ff6c0f259c21afbf37c': 'Key de5aa1ad8b41d89850348ff6c0f259c21afbf37c not found in /da5_fast/All.sha1c/commit_94.tch'}

 48%|████▊     | 1084/2243 [19:27<20:52,  1.08s/it]

Got Errors {'e24637644adb3ee5adf81697eedc5038b3537e7d': 'Key e24637644adb3ee5adf81697eedc5038b3537e7d not found in /da5_fast/All.sha1c/commit_98.tch'}

 50%|████▉     | 1114/2243 [20:00<20:17,  1.08s/it]

Got Errors {'ec703f30e93eaacc874e7649c95e3a8e5cd6d7a9': 'Key ec703f30e93eaacc874e7649c95e3a8e5cd6d7a9 not found in /da5_fast/All.sha1c/commit_108.tch'}

 53%|█████▎    | 1182/2243 [21:13<19:02,  1.08s/it]

Got Errors {'010bc5f3dab81862cbc5a0a77877f17c4b9b76e4': 'Key 010bc5f3dab81862cbc5a0a77877f17c4b9b76e4 not found in /da5_fast/All.sha1c/commit_1.tch'}

 53%|█████▎    | 1186/2243 [21:17<19:02,  1.08s/it]

Got Errors {'025ce8bf002a5c12f0df0659e1842e13ce9f8350': 'Key 025ce8bf002a5c12f0df0659e1842e13ce9f8350 not found in /da5_fast/All.sha1c/commit_2.tch'}

 56%|█████▌    | 1251/2243 [22:27<17:43,  1.07s/it]

Got Errors {'16a01f29096f07d5e97d754b44d8320186cfddbc': 'Key 16a01f29096f07d5e97d754b44d8320186cfddbc not found in /da5_fast/All.sha1c/commit_22.tch'}

 56%|█████▋    | 1265/2243 [22:42<17:28,  1.07s/it]

Got Errors {'1b24b69294d5e1763113b4ea513c6c42b6518e3f': 'Key 1b24b69294d5e1763113b4ea513c6c42b6518e3f not found in /da5_fast/All.sha1c/commit_27.tch'}

 56%|█████▋    | 1266/2243 [22:43<17:27,  1.07s/it]

Got Errors {'1b378981463c75aa2df53345cac2057b433f3333': 'Key 1b378981463c75aa2df53345cac2057b433f3333 not found in /da5_fast/All.sha1c/commit_27.tch'}

 59%|█████▉    | 1325/2243 [23:46<16:23,  1.07s/it]

Got Errors {'2c0ba30cd9670079668c73b0a98220d174d08970': 'Key 2c0ba30cd9670079668c73b0a98220d174d08970 not found in /da5_fast/All.sha1c/commit_44.tch'}

 60%|██████    | 1350/2243 [24:13<15:57,  1.07s/it]

Got Errors {'33b4e0883710a42d80d1fe3605beda6a47a4cd78': 'Key 33b4e0883710a42d80d1fe3605beda6a47a4cd78 not found in /da5_fast/All.sha1c/commit_51.tch'}

 60%|██████    | 1352/2243 [24:16<15:58,  1.08s/it]

Got Errors {'34372237b3b13d4ca2ab7b7389b11c7a32e7bd83': 'Key 34372237b3b13d4ca2ab7b7389b11c7a32e7bd83 not found in /da5_fast/All.sha1c/commit_52.tch'}

 61%|██████    | 1359/2243 [24:23<15:53,  1.08s/it]

Got Errors {'362eca323552686cea69949057bc59fedfcea435': 'Key 362eca323552686cea69949057bc59fedfcea435 not found in /da5_fast/All.sha1c/commit_54.tch'}

 62%|██████▏   | 1380/2243 [24:46<15:23,  1.07s/it]

Got Errors {'3ce175b9a239742f669b0f68f0f31271dda2c1d4': 'Key 3ce175b9a239742f669b0f68f0f31271dda2c1d4 not found in /da5_fast/All.sha1c/commit_60.tch'}

 62%|██████▏   | 1389/2243 [24:55<15:16,  1.07s/it]

Got Errors {'3f59e02fb2f48f703b68ea2f2a4bdc1a91ea64da': 'Key 3f59e02fb2f48f703b68ea2f2a4bdc1a91ea64da not found in /da5_fast/All.sha1c/commit_63.tch'}

 62%|██████▏   | 1401/2243 [25:08<15:04,  1.07s/it]

Got Errors {'431cfc61bafc07af077bac15e5be927af78d05a1': 'Key 431cfc61bafc07af077bac15e5be927af78d05a1 not found in /da5_fast/All.sha1c/commit_67.tch'}

 64%|██████▎   | 1429/2243 [25:38<14:34,  1.07s/it]

Got Errors {'4b97e84d7c81ee9868415a995a4fc7515eb2c58e': 'Key 4b97e84d7c81ee9868415a995a4fc7515eb2c58e not found in /da5_fast/All.sha1c/commit_75.tch'}

 66%|██████▌   | 1472/2243 [26:24<13:47,  1.07s/it]

Got Errors {'584abe9f2da8559b8fe48a060a982dfb103a2707': 'Key 584abe9f2da8559b8fe48a060a982dfb103a2707 not found in /da5_fast/All.sha1c/commit_88.tch'}

 68%|██████▊   | 1527/2243 [27:24<12:48,  1.07s/it]

Got Errors {'6832db011e1fa34de1689f4f7af5a818b4f1f905': 'Key 6832db011e1fa34de1689f4f7af5a818b4f1f905 not found in /da5_fast/All.sha1c/commit_104.tch'}

 68%|██████▊   | 1534/2243 [27:31<12:46,  1.08s/it]

Got Errors {'6a4c4f0f820b11881296faf61f60ead480f83ae2': 'Key 6a4c4f0f820b11881296faf61f60ead480f83ae2 not found in /da5_fast/All.sha1c/commit_106.tch'}

 70%|███████   | 1579/2243 [28:20<11:55,  1.08s/it]

Got Errors {'777b92a920c91166ac0da93fef5564aace92a7a7': 'Key 777b92a920c91166ac0da93fef5564aace92a7a7 not found in /da5_fast/All.sha1c/commit_119.tch'}

 71%|███████   | 1584/2243 [28:25<11:49,  1.08s/it]

Got Errors {'78c4c70792dfbcee522aa939716229d40dd473b4': 'Key 78c4c70792dfbcee522aa939716229d40dd473b4 not found in /da5_fast/All.sha1c/commit_120.tch'}

 71%|███████   | 1586/2243 [28:27<11:44,  1.07s/it]

Got Errors {'795162d62e1ce3e4dd09b17475068b12b4108448': 'Key 795162d62e1ce3e4dd09b17475068b12b4108448 not found in /da5_fast/All.sha1c/commit_121.tch'}

 72%|███████▏  | 1613/2243 [28:56<11:18,  1.08s/it]

Got Errors {'80bcd3badbf63c0f1640214434ddc47d4217422c': 'Key 80bcd3badbf63c0f1640214434ddc47d4217422c not found in /da5_fast/All.sha1c/commit_0.tch'}

 73%|███████▎  | 1632/2243 [29:17<10:56,  1.07s/it]

Got Errors {'86195f4f5e3882845b656cf7dd24dd645d3a52f8': 'Key 86195f4f5e3882845b656cf7dd24dd645d3a52f8 not found in /da5_fast/All.sha1c/commit_6.tch'}

 78%|███████▊  | 1746/2243 [31:19<08:53,  1.07s/it]

Got Errors {'a8671ceff3f8ec1e667a07484d0d84b6eb23f709': 'Key a8671ceff3f8ec1e667a07484d0d84b6eb23f709 not found in /da5_fast/All.sha1c/commit_40.tch'}

 78%|███████▊  | 1749/2243 [31:22<08:49,  1.07s/it]

Got Errors {'a9340e5e35fefa901b2682b3c70794ede8afa89b': 'Key a9340e5e35fefa901b2682b3c70794ede8afa89b not found in /da5_fast/All.sha1c/commit_41.tch'}

 80%|████████  | 1797/2243 [32:14<07:59,  1.07s/it]

Got Errors {'b744564bb141478ea799e25ed0393d3ffaeda25c': 'Key b744564bb141478ea799e25ed0393d3ffaeda25c not found in /da5_fast/All.sha1c/commit_55.tch'}

 80%|████████  | 1805/2243 [32:22<07:49,  1.07s/it]

Got Errors {'b9aa52258fa68f4120e1bd1923e83081b0b11c6b': 'Key b9aa52258fa68f4120e1bd1923e83081b0b11c6b not found in /da5_fast/All.sha1c/commit_57.tch'}

 81%|████████  | 1810/2243 [32:28<07:44,  1.07s/it]

Got Errors {'bb414fe043aaf596350a04c53e1e66d7c197af3d': 'Key bb414fe043aaf596350a04c53e1e66d7c197af3d not found in /da5_fast/All.sha1c/commit_59.tch'}

 82%|████████▏ | 1840/2243 [33:00<07:13,  1.08s/it]

Got Errors {'c4718290efcfc1ff5c087f0576f65b5ba9d22b67': 'Key c4718290efcfc1ff5c087f0576f65b5ba9d22b67 not found in /da5_fast/All.sha1c/commit_68.tch'}

 85%|████████▍ | 1905/2243 [34:10<06:04,  1.08s/it]

Got Errors {'d864d00cb67288360a9901d368be4fd4c1e2af85': 'Key d864d00cb67288360a9901d368be4fd4c1e2af85 not found in /da5_fast/All.sha1c/commit_88.tch'}

 85%|████████▌ | 1907/2243 [34:12<06:00,  1.07s/it]

Got Errors {'d8fe9464f9efadc246ada38b9206d2d545ad6c81': 'Key d8fe9464f9efadc246ada38b9206d2d545ad6c81 not found in /da5_fast/All.sha1c/commit_88.tch'}

 87%|████████▋ | 1948/2243 [34:56<05:17,  1.08s/it]

Got Errors {'e60a817afb958d9e9124d65ef7b4d11e6b26fe21': 'Key e60a817afb958d9e9124d65ef7b4d11e6b26fe21 not found in /da5_fast/All.sha1c/commit_102.tch'}

 88%|████████▊ | 1978/2243 [35:28<04:45,  1.08s/it]

Got Errors {'eee44114b5db59e99603450fe610ee8bce876eab': 'Key eee44114b5db59e99603450fe610ee8bce876eab not found in /da5_fast/All.sha1c/commit_110.tch'}

100%|██████████| 2243/2243 [40:14<00:00,  1.08s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,00c5bbd0d4fdddc2a6f2ffec96b4a6472b4c7bef,2c83dbede5978041b1842b7d0af5db7c15eee65c,[01807489e8d20b4b291770b72133f67b2ac8bf87],AndraIonescu <andradenis.ionescu@gmail.com>,1571149530,+0200,AndraIonescu <andradenis.ionescu@gmail.com>,1571149530,+0200,Added the final correlation clustering framewo...,00c5bbd0d4fdddc2a6f2ffec96b4a6472b4c7bef,delftdata_valentine
1,01807489e8d20b4b291770b72133f67b2ac8bf87,e581959571f850b0089cc9a4a183e40329ec9e74,[ba3da28481cfaf045b80a758c9ee9c5b376475a4],AndraIonescu <andradenis.ionescu@gmail.com>,1571142631,+0200,AndraIonescu <andradenis.ionescu@gmail.com>,1571142631,+0200,bug fixes\n,01807489e8d20b4b291770b72133f67b2ac8bf87,delftdata_valentine

In [4]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '00c5bbd0d4fdddc2a6f2ffec96b4a6472b4c7bef', 'tree': '2c83dbede5978041b1842b7d0af5db7c15eee65c', 'parent': ['01807489e8d20b4b291770b72133f67b2ac8bf87'], 'author': 'AndraIonescu <andradenis.ionescu@gmail.com>', 'author_time': 1571149530, 'author_tz': '+0200', 'committer': 'AndraIonescu <andradenis.ionescu@gmail.com>', 'committer_time': 1571149530, 'committer_tz': '+0200', 'message': 'Added the final correlation clustering framework\n'}

In [5]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [6]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,jump-dev_sumofsquares.jl,00c5bbd0d4fdddc2a6f2ffec96b4a6472b4c7bef,AndraIonescu <andradenis.ionescu@gmail.com>,1571149530,Added the final correlation clustering framewo...

In [7]:
#mode a means append, so you have all your projects in the same file
yournetid='dlong37'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github